import {
    Code,
    Pen,
    FileImage,
    Lock,
    Type,
    QrCode,
    Scale,
    Timer,
    BoxSelect,
    Palette,
    Fingerprint,
    Keyboard,
    Database,
    RefreshCcw,
    Binary,
    Clock,
    LucideIcon,
    Youtube,
    ALargeSmall,
    Percent,
    Calendar,
    Scaling,
    Calculator,
    CircleDollarSign,
    Activity,
    FileUp,
    ShieldCheck,
    MessageCircle,
    TimerReset,
    Hash,
    Twitter,
    Link,
    Shuffle,
    Instagram,
    Facebook,
    Linkedin,
    Video,
    ImagePlus,
    Eraser,
    PaintBucket,
    Receipt,
    FileText,
    TrendingUp,
    Smile,
    Quote
} from "lucide-react"

export type ToolCategory = "developer" | "design" | "security" | "media" | "text" | "social" | "general" | "math" | "finance" | "health" | "pdf"

export interface ToolMetadata {
    slug: string
    name: string
    description: string
    category: ToolCategory
    icon: LucideIcon
    isNew?: boolean
    isPopular?: boolean
    isPremium?: boolean
}

export const tools: ToolMetadata[] = [
    {
        slug: "base64-encoder",
        name: "Base64 Encoder",
        description: "Encode text to Base64 or decode Base64 strings securely.",
        category: "developer",
        icon: Binary,
        isNew: true,
    },
    {
        slug: "url-encoder",
        name: "URL Encoder",
        description: "Encode and decode URL-encoded text (percent-encoding).",
        category: "developer",
        icon: Link,
        isNew: true,
    },

    // --- Developer Tools ---
    {
        slug: "json-formatter",
        name: "JSON Formatter",
        description: "Free Online JSON Formatter, Minifier & Validator.",
        category: "developer",
        icon: Code,
        isPopular: true,
    },
    {
        slug: "sql-formatter",
        name: "SQL Formatter",
        description: "Free Online SQL Formatter & Prettifier for developers.",
        category: "developer",
        icon: Database,
        isNew: true,
    },
    {
        slug: "css-flexbox-playground",
        name: "CSS Flexbox Playground",
        description: "Visual generator for CSS Flexbox layouts. Learn and build faster.",
        category: "developer",
        icon: BoxSelect,
        isNew: true,
    },
    {
        slug: "jwt-decoder",
        name: "JWT Decoder",
        description: "Free Online JWT Decoder. Debug tokens securely in your browser.",
        category: "developer",
        icon: Lock,
        isNew: true,
    },
    {
        slug: "uuid-generator",
        name: "UUID Generator",
        description: "Free Bulk UUID Generator (v4). Create unique IDs instantly.",
        category: "developer",
        icon: Fingerprint,
        isNew: true,
    },
    {
        slug: "cron-generator",
        name: "Cron Generator",
        description: "Free Cron Expression Generator with next run preview.",
        category: "developer",
        icon: Clock,
        isNew: true,
    },
    {
        slug: "keycode-info",
        name: "Keycode Info",
        description: "Online Keycode Finder. Get JavaScript event key codes visually.",
        category: "developer",
        icon: Keyboard,
        isNew: true,
    },

    // --- Design Tools ---
    {
        slug: "image-converter",
        name: "Image Converter",
        description: "Free Image Converter. Convert JPG, PNG to WebP securely.",
        category: "media",
        icon: FileImage,
        isPopular: true,
    },
    {
        slug: "svg-to-png",
        name: "SVG to PNG/JPG",
        description: "Convert SVG vectors to high-quality PNG or JPG images.",
        category: "media",
        icon: FileImage,
        isNew: true,
    },
    {
        slug: "box-shadow-generator",
        name: "Box Shadow Generator",
        description: "Free CSS Box Shadow Generator. Visual design tool for developers.",
        category: "design",
        icon: BoxSelect,
        isNew: true,
    },
    {
        slug: "gradient-generator",
        name: "Gradient Generator",
        description: "Free CSS Gradient Generator. Create beautiful linear & radial gradients.",
        category: "design",
        icon: Palette,
        isNew: true,
    },

    // --- Security Tools ---
    {
        slug: "password-generator",
        name: "Password Generator",
        description: "Free Strong Password Generator. Create secure passwords instantly.",
        category: "security",
        icon: Lock,
        isPopular: true,
    },

    // --- Text Tools ---
    {
        slug: "word-counter",
        name: "Word Counter",
        description: "Free Online Word Counter & Character Count Tool.",
        category: "text",
        icon: Type,
    },
    {
        slug: "markdown-editor",
        name: "Markdown Editor",
        description: "Write and preview Markdown with a split-pane interface.",
        category: "text",
        icon: Type,
        isNew: true,
    },
    {
        slug: "diff-viewer",
        name: "Diff Viewer",
        description: "Free Text Diff Viewer. Compare strings and find differences online.",
        category: "text",
        icon: RefreshCcw,
        isNew: true,
    },

    {
        slug: "lorem-ipsum-generator",
        name: "Lorem Ipsum",
        description: "Generate placeholder text: paragraphs, sentences, or words.",
        category: "text",
        icon: Type,
        isNew: true,
        isPopular: true,
    },
    {
        slug: "text-to-handwriting",
        name: "Text to Handwriting",
        description: "Convert typed text into handwriting-style notes.",
        category: "text",
        icon: Pen,
        isNew: true,
        isPopular: true,
    },

    // --- General/Consumer Tools ---
    {
        slug: "qr-code-generator",
        name: "QR Code Generator",
        description: "Free QR Code Generator with Logo support. High-quality PNG download.",
        category: "general",
        icon: QrCode,
        isNew: true,
    },
    {
        slug: "unit-converter",
        name: "Unit Converter",
        description: "Free Unit Converter. Convert Length, Weight, Temperature with formulas.",
        category: "general",
        icon: Scale,
        isNew: true,
        isPopular: true,
    },
    {
        slug: "stopwatch",
        name: "Stopwatch & Timer",
        description: "Free Online Stopwatch with Laps and Countdown Timer.",
        category: "general",
        icon: Timer,
        isNew: true,
    },
    {
        slug: "list-randomizer",
        name: "List Randomizer",
        description: "Randomize the order of items in a list or text file.",
        category: "general",
        icon: Shuffle,
        isNew: true,
        isPopular: true,
    },
    // --- Social Tools ---
    {
        slug: "youtube-thumbnail",
        name: "YouTube Thumbnail",
        description: "Download high-quality YouTube thumbnails and images.",
        category: "social",
        icon: Youtube,
        isNew: true,
    },

    // --- Math Tools ---
    {
        slug: "percentage-calculator",
        name: "Percentage Calculator",
        description: "Calculate percentages, percentage increase/decrease, and more.",
        category: "math",
        icon: Percent,
        isNew: true,
    },

    // --- New Consumer Tools ---
    {
        slug: "case-converter",
        name: "Case Converter",
        description: "Convert text between Uppercase, Lowercase, Title Case & more.",
        category: "text",
        icon: ALargeSmall,
        isNew: true,
    },
    {
        slug: "age-calculator",
        name: "Age Calculator",
        description: "Calculate your exact age in years, months, and days.",
        category: "general",
        icon: Calendar,
        isNew: true,
    },
    {
        slug: "image-resizer",
        name: "Image Resizer",
        description: "Resize images by pixel dimensions or percentage online.",
        category: "media",
        icon: Scaling,
        isNew: true,
    },

    // --- Finance Tools ---
    {
        slug: "loan-calculator",
        name: "Loan Calculator",
        description: "Calculate monthly payments (EMI) and total interest for loans.",
        category: "finance",
        icon: CircleDollarSign,
        isNew: true,
    },

    // --- Health Tools ---
    {
        slug: "bmi-calculator",
        name: "BMI Calculator",
        description: "Calculate Body Mass Index (BMI) and check weight categories.",
        category: "health",
        icon: Activity,
        isNew: true,
    },

    // --- PDF Tools ---
    {
        slug: "image-to-pdf",
        name: "Image to PDF",
        description: "Convert JPG/PNG images to a single PDF document online.",
        category: "pdf",
        icon: FileUp,
        isNew: true,
    },
    {
        slug: "signature-generator",
        name: "Signature Generator",
        description: "Create digital signatures and sign PDF documents online.",
        category: "pdf",
        icon: Pen,
        isNew: true,
        isPopular: true,
    },
    {
        slug: "sign-pdf",
        name: "Sign PDF Online",
        description: "Upload and sign PDF documents. Add signatures to all pages instantly.",
        category: "pdf",
        icon: Pen,
        isNew: true,
    },

    // --- Security Tools Additions ---
    {
        slug: "password-strength",
        name: "Password Strength",
        description: "Test how strong your password is and estimate crack time.",
        category: "security",
        icon: ShieldCheck,
        isNew: true,
    },

    // --- Social Tools Additions ---
    {
        slug: "social-media-preview",
        name: "Social Media Preview",
        description: "Preview how your links look on Facebook, Twitter, LinkedIn & Google.",
        category: "social",
        icon: MessageCircle,
        isNew: true,
    },
    {
        slug: "whatsapp-link",
        name: "WhatsApp Link",
        description: "Generate direct WhatsApp links with pre-filled messages.",
        category: "social",
        icon: MessageCircle,
        isNew: true,
    },
    {
        slug: "instagram-hashtags",
        name: "Instagram Hashtags",
        description: "Generate trending hashtags for Instagram to boost reach.",
        category: "social",
        icon: Hash,
        isNew: true,
    },
    {
        slug: "tweet-to-image",
        name: "Tweet to Image",
        description: "Convert tweets into beautiful shareable images.",
        category: "social",
        icon: Twitter,
        isNew: true,
    },
    {
        slug: "instagram-post-generator",
        name: "Instagram Post Generator",
        description: "Create realistic fake Instagram posts with custom content.",
        category: "social",
        icon: Instagram,
        isNew: true,
    },
    {
        slug: "facebook-post-generator",
        name: "Facebook Post Generator",
        description: "Generate lifelike Facebook post mockups with reactions.",
        category: "social",
        icon: Facebook,
        isNew: true,
    },
    {
        slug: "linkedin-post-generator",
        name: "LinkedIn Post Generator",
        description: "Create professional fake LinkedIn posts with custom headlines.",
        category: "social",
        icon: Linkedin,
        isNew: true,
    },

    // --- Productivity/General ---
    {
        slug: "pomodoro-timer",
        name: "Pomodoro Timer",
        description: "Maximize focus with this customizable Pomodoro technique timer.",
        category: "general",
        icon: TimerReset,
        isNew: true,
    },

    // --- NEW: Popular Media Tools ---
    {
        slug: "video-enhancer",
        name: "AI Video Enhancer",
        description: "Enhance video quality - upscale resolution, reduce noise, stabilize footage online for free.",
        category: "media",
        icon: Video,
        isNew: true,
        isPopular: true,
        isPremium: true,
    },
    {
        slug: "photo-enhancer",
        name: "Photo Enhancer AI",
        description: "Enhance photo quality with AI - auto color correction, sharpen, denoise, and upscale images online.",
        category: "media",
        icon: ImagePlus,
        isNew: true,
        isPopular: true,
        isPremium: true,
    },
    {
        slug: "watermark-remover",
        name: "Watermark Remover",
        description: "Remove watermarks from photos and videos online - AI-powered watermark eraser for images.",
        category: "media",
        icon: Eraser,
        isNew: true,
        isPopular: true,
    },
    {
        slug: "image-editor",
        name: "Online Image Editor",
        description: "Professional online image editor. Crop, resize, add filters, text, and effects.",
        category: "design",
        icon: PaintBucket,
        isNew: true,
        isPopular: true,
    },
    {
        slug: "compound-interest",
        name: "Compound Interest",
        description: "Calculate how your savings grow over time with compound interest. View growth charts and wealth projections.",
        category: "finance",
        icon: TrendingUp,
        isNew: true,
        isPopular: true,
    },
    {
        slug: "tip-calculator",
        name: "Tip Calculator",
        description: "Quickly calculate tips and split bills with friends. Simple, clean, and private.",
        category: "finance",
        icon: Receipt,
        isNew: true,
    },
    {
        slug: "discount-calculator",
        name: "Discount Calculator",
        description: "Find the final price after discounts and taxes instantly. Perfect for shopping.",
        category: "finance",
        icon: Percent,
        isNew: true,
    },
    // --- Business Suite ---
    {
        slug: "invoice-generator",
        name: "Invoice Generator",
        description: "Create professional invoices with custom branding, taxes, and discounts. 100% private.",
        category: "finance",
        icon: FileText,
        isNew: true,
        isPopular: true,
        isPremium: true,
    },
    {
        slug: "business-quote-generator",
        name: "Business Quote Builder",
        description: "Generate professional business quotes and estimates for your clients.",
        category: "finance",
        icon: FileText,
        isNew: true,
    },
    {
        slug: "receipt-generator",
        name: "Receipt Generator",
        description: "Create quick, professional payment receipts for your business or freelance work.",
        category: "finance",
        icon: Receipt,
        isNew: true,
    },
    {
        slug: "estimate-generator",
        name: "Estimate Generator",
        description: "Create detailed project estimates and download them as PDF.",
        category: "finance",
        icon: Calculator,
        isNew: true,
    },
    // --- Creative Suite ---
    {
        slug: "meme-generator",
        name: "Meme Generator",
        description: "Create viral memes using trending templates or your own images. High-quality exports without watermarks.",
        category: "design",
        icon: Smile,
        isNew: true,
    },
    {
        slug: "social-quote-generator",
        name: "Social Quote Creator",
        description: "Turn quotes into beautiful cinematic posts for Instagram and social media.",
        category: "design",
        icon: Quote,
        isNew: true,
    },
    {
        slug: "scientific-calculator",
        name: "Scientific Calculator",
        description: "Advanced scientific calculator with trigonometry, logarithms, and more. Simple and Pro modes.",
        category: "math",
        icon: Calculator,
        isNew: true,
        isPopular: true,
    },
]

export const categories: { id: ToolCategory; label: string; icon: LucideIcon }[] = [
    { id: "developer", label: "Developer", icon: Code },
    { id: "design", label: "Design", icon: Palette },
    { id: "media", label: "Media", icon: FileImage },
    { id: "security", label: "Security", icon: Lock },
    { id: "text", label: "Text", icon: Type },
    { id: "social", label: "Social", icon: Youtube },
    { id: "math", label: "Math", icon: Calculator },
    { id: "finance", label: "Finance", icon: CircleDollarSign },
    { id: "health", label: "Health", icon: Activity },
    { id: "pdf", label: "PDF", icon: FileUp },
    { id: "general", label: "General", icon: RefreshCcw },
]
